
version: '3.9'

services:
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media

    expose:
      - "8000"
    environment:
      - ALLOWED_HOSTS=peykhaksang.com,www.peykhaksang.com
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=peykhaks_user1
      - POSTGRES_PASSWORD=peykhaks_pass1
      - POSTGRES_DB=peykhaks_db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
    ports:
      - "8001:80"
volumes:
  postgres_data:
  static_volume:
  media_volume:
  