# Generated by Django 4.2 on 2024-12-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته بندی')),
                ('name_fa', models.CharField(max_length=200, null=True, verbose_name='نام دسته بندی')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='نام دسته بندی')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.category')),
            ],
            options={
                'verbose_name': 'دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی مقالات',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='PopupAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('alert_title', models.TextField(blank=True, null=True, verbose_name='عنوان آلرت')),
                ('alert_control', models.BooleanField(default=False, verbose_name='نمایش آلرت')),
                ('popup_title', models.TextField(blank=True, null=True, verbose_name='عنوان پاپ آپ')),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='popup_images/', verbose_name='تصویر پاپ آپ')),
                ('popup_control', models.BooleanField(default=False, verbose_name='نمایش پاپ آپ')),
            ],
            options={
                'verbose_name': 'پاپ آپ و آلرت',
                'verbose_name_plural': 'پاپ آپ و آلرت',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ')),
                ('desc_1', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول')),
                ('desc_1_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول')),
                ('desc_1_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول')),
                ('desc_1_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول')),
                ('desc_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم')),
                ('desc_2_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم')),
                ('desc_2_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم')),
                ('desc_2_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم')),
                ('post_summery', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله')),
                ('post_summery_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله')),
                ('post_summery_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله')),
                ('post_summery_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله')),
                ('image', models.ImageField(default='posts/thumbnails/squre_images/1.jpg', upload_to='posts/thumbnails/%Y/%m', verbose_name='تصویر اصلی')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')),
                ('publish_date', models.DateTimeField(null=True, verbose_name='زمان انتشار')),
                ('total_views', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('blog_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=100, null=True, verbose_name='وضعیت انتشار')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='website.category')),
            ],
            options={
                'verbose_name': 'مقالات',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-publish_date',),
            },
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام تصویر')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='نام تصویر')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='نام تصویر')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='نام تصویر')),
                ('alt', models.CharField(max_length=255, verbose_name='متن جایگزین')),
                ('alt_fa', models.CharField(max_length=255, null=True, verbose_name='متن جایگزین')),
                ('alt_en', models.CharField(max_length=255, null=True, verbose_name='متن جایگزین')),
                ('alt_ar', models.CharField(max_length=255, null=True, verbose_name='متن جایگزین')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان تگ')),
                ('name_fa', models.CharField(max_length=200, null=True, verbose_name='عنوان تگ')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='عنوان تگ')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ تگ')),
            ],
            options={
                'verbose_name': 'تگ ها',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='TagsSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سئو')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('description', models.TextField(verbose_name='توضیحات سئو')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('description_ar', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو')),
                ('tags_seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttags', to='website.tags')),
            ],
            options={
                'verbose_name': 'سئو تگ ها',
                'verbose_name_plural': 'سئو تگ ها',
            },
        ),
        migrations.CreateModel(
            name='PostSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان سئو')),
                ('title_fa', models.CharField(max_length=50, null=True, verbose_name='عنوان سئو')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='عنوان سئو')),
                ('title_ar', models.CharField(max_length=50, null=True, verbose_name='عنوان سئو')),
                ('description', models.TextField(max_length=200, verbose_name='توضیحات سئو')),
                ('description_fa', models.TextField(max_length=200, null=True, verbose_name='توضیحات سئو')),
                ('description_en', models.TextField(max_length=200, null=True, verbose_name='توضیحات سئو')),
                ('description_ar', models.TextField(max_length=200, null=True, verbose_name='توضیحات سئو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='website.post')),
            ],
            options={
                'verbose_name': 'سئو مقالات',
                'verbose_name_plural': 'سئو مقالات',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='website.tags'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('name_fa', models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی')),
                ('name_ar', models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('body_fa', models.TextField(null=True, verbose_name='متن پیام')),
                ('body_en', models.TextField(null=True, verbose_name='متن پیام')),
                ('body_ar', models.TextField(null=True, verbose_name='متن پیام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('active', models.BooleanField(default=True, verbose_name=' فعال')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CategorySEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سئو')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو')),
                ('description', models.TextField(verbose_name='توضیحات سئو')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('description_ar', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو')),
                ('Category_seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='website.category')),
            ],
            options={
                'verbose_name': 'سئو دسته بندی ها',
                'verbose_name_plural': 'سئو دسته بندی ها',
            },
        ),
    ]
