# Generated by Django 4.2 on 2024-11-05 11:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی مقالات', 'verbose_name_plural': 'دسته بندی مقالات'},
        ),
        migrations.AlterModelOptions(
            name='categoryseo',
            options={'verbose_name': 'سئو دسته بندی ها', 'verbose_name_plural': 'سئو دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',), 'verbose_name': 'مقالات', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='postseo',
            options={'verbose_name': 'سئو مقالات', 'verbose_name_plural': 'سئو مقالات'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'تگ ها', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterModelOptions(
            name='tagsseo',
            options={'verbose_name': 'سئو تگ ها', 'verbose_name_plural': 'سئو تگ ها'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fa',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ دسته بندی'),
        ),
        migrations.AddField(
            model_name='categoryseo',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='categoryseo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='categoryseo',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='categoryseo',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='categoryseo',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='categoryseo',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_ar',
            field=models.TextField(null=True, verbose_name='متن پیام'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en',
            field=models.TextField(null=True, verbose_name='متن پیام'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_fa',
            field=models.TextField(null=True, verbose_name='متن پیام'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_status_ar',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=100, null=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_status_en',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=100, null=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_status_fa',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=100, null=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc_1_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc_1_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc_1_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc_2_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc_2_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc_2_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_summery_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_summery_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_summery_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='postseo',
            name='description_ar',
            field=models.TextField(max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='postseo',
            name='description_en',
            field=models.TextField(max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='postseo',
            name='description_fa',
            field=models.TextField(max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='postseo',
            name='title_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='postseo',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='postseo',
            name='title_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='alt_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='متن جایگزین'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='alt_en',
            field=models.CharField(max_length=255, null=True, verbose_name='متن جایگزین'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='alt_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='متن جایگزین'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='نام تصویر'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام تصویر'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام تصویر'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان تگ'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان تگ'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان تگ'),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ تگ'),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ تگ'),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug_fa',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ تگ'),
        ),
        migrations.AddField(
            model_name='tagsseo',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='tagsseo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='tagsseo',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='tagsseo',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='tagsseo',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='tagsseo',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ دسته بندی'),
        ),
        migrations.AlterField(
            model_name='categoryseo',
            name='description',
            field=models.TextField(verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='categoryseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو'),
        ),
        migrations.AlterField(
            model_name='categoryseo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name=' فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='تاریخ به روزرسانی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=100, null=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت '),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_1',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن اول'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_2',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن دوم'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/thumbnails/squre_images/1.jpg', upload_to='posts/thumbnails/%Y/%m', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_summery',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='postseo',
            name='description',
            field=models.TextField(max_length=200, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='postseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو'),
        ),
        migrations.AlterField(
            model_name='postseo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان تگ'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ تگ'),
        ),
        migrations.AlterField(
            model_name='tagsseo',
            name='description',
            field=models.TextField(verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='tagsseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو'),
        ),
        migrations.AlterField(
            model_name='tagsseo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان سئو'),
        ),
    ]
