# Generated by Django 4.2 on 2024-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_category_options_alter_categoryseo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_status_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_status_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_status_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug_fa',
        ),
    ]
