# Generated by Django 4.2 on 2024-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_category_slug_ar_remove_category_slug_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255, verbose_name='عنوان آلرت')),
                ('alert_control', models.BooleanField(default=False, verbose_name='نمایش آلرت')),
                ('popup_title', models.CharField(max_length=255, verbose_name='عنوان پاپ آپ')),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='popup_images/', verbose_name='تصویر پاپ آپ')),
                ('popup_control', models.BooleanField(default=False, verbose_name='نمایش پاپ آپ')),
            ],
            options={
                'verbose_name': 'پاپ آپ و آلرت',
                'verbose_name_plural': 'پاپ آپ و آلرت',
            },
        ),
    ]
