# Generated by Django 4.2 on 2024-12-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_popupalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupalert',
            name='alert_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان آلرت'),
        ),
        migrations.AlterField(
            model_name='popupalert',
            name='popup_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان پاپ آپ'),
        ),
    ]
