# Generated by Django 4.2 on 2024-12-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_popupalert_alert_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupalert',
            name='alert_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان آلرت'),
        ),
        migrations.AlterField(
            model_name='popupalert',
            name='popup_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان پاپ آپ'),
        ),
    ]
