# Generated by Django 4.2 on 2024-11-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی محصولات',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان لیست قیمت')),
                ('title_fa', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان لیست قیمت')),
                ('title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان لیست قیمت')),
                ('title_ar', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان لیست قیمت')),
                ('upload_date', models.TextField(blank=True, null=True, verbose_name='تاریخ به روز رسانی لیست قیمت')),
                ('upload_date_fa', models.TextField(blank=True, null=True, verbose_name='تاریخ به روز رسانی لیست قیمت')),
                ('upload_date_en', models.TextField(blank=True, null=True, verbose_name='تاریخ به روز رسانی لیست قیمت')),
                ('upload_date_ar', models.TextField(blank=True, null=True, verbose_name='تاریخ به روز رسانی لیست قیمت')),
                ('beton_1_document', models.FileField(blank=True, null=True, upload_to='doc/beton1/', verbose_name='فایل بتن پایه یک')),
                ('beton_2_document', models.FileField(blank=True, null=True, upload_to='doc/beton2/', verbose_name='فایل بتن پایه دو')),
                ('beton_3_document', models.FileField(blank=True, null=True, upload_to='doc/beton3/', verbose_name='فایل بتن پایه سه')),
                ('khak_1_document', models.FileField(blank=True, null=True, upload_to='doc/khak1/', verbose_name='فایل خاک پایه یک')),
                ('khak_2_document', models.FileField(blank=True, null=True, upload_to='doc/khak2/', verbose_name='فایل خاک پایه دو')),
                ('khak_3_document', models.FileField(blank=True, null=True, upload_to='doc/khak3/', verbose_name='فایل خاک پایه سه')),
            ],
            options={
                'verbose_name': 'لیست قیمت محصولات',
                'verbose_name_plural': 'لیست قیمت محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان محصول')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان محصول')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='اسلاگ محصول')),
                ('Code', models.CharField(max_length=15, null=True, unique=True, verbose_name='کد محصول')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن محصول')),
                ('description_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن محصول')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن محصول')),
                ('description_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='متن محصول')),
                ('summery', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه متن')),
                ('summery_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه متن')),
                ('summery_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه متن')),
                ('summery_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='خلاصه متن')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت محصول')),
                ('price_fa', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='قیمت محصول')),
                ('price_en', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='قیمت محصول')),
                ('price_ar', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='قیمت محصول')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('offer_price_fa', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('offer_price_en', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('offer_price_ar', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='تصویر عکس')),
                ('status', models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=2, verbose_name='وضعیت محصول')),
                ('avg_rate', models.FloatField(default=0.0, verbose_name='نمره محصول')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='زمان به روز رسانی')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('publish_date', models.DateTimeField(null=True, verbose_name='زمان انتشار')),
                ('total_views', models.IntegerField(default='1k', verbose_name='مجموع بازدید')),
                ('is_active', models.CharField(blank=True, choices=[('active', 'active'), ('not_active', 'not_active')], default='not_active', max_length=100, null=True, verbose_name='فعال بودن')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('size', models.CharField(choices=[('light', 'light'), ('Heavy', 'Heavy'), ('Medium', 'Medium')], default='Medium', max_length=255, verbose_name='اندازه')),
                ('guarantee', models.BooleanField(default=True, verbose_name='گارانتی')),
                ('time_to_bring', models.CharField(blank=True, max_length=255, null=True, verbose_name='زمان ارسال')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی محصولات',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='StandardAASHTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FileField(blank=True, null=True, upload_to='standards/AASHTO/')),
            ],
            options={
                'verbose_name': 'استاندارد آشو',
                'verbose_name_plural': 'استاندارد آشو',
            },
        ),
        migrations.CreateModel(
            name='StandardASTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FileField(blank=True, null=True, upload_to='standards/ASTM/')),
            ],
            options={
                'verbose_name': 'استاندارد ASTM',
                'verbose_name_plural': 'استاندارد ASTM',
            },
        ),
        migrations.CreateModel(
            name='StandardISIRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FileField(blank=True, null=True, upload_to='standards/ISIRI/')),
            ],
            options={
                'verbose_name': 'استاندارد ایران',
                'verbose_name_plural': 'استاندارد ایران',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'تگ ها',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='WishlistProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصولات مورد علاقه',
                'verbose_name_plural': 'محصولات مورد علاقه',
            },
        ),
        migrations.CreateModel(
            name='TagsSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سئو تگ')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو تگ')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو تگ')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو تگ')),
                ('description', models.TextField(verbose_name='توضیحات سئو تگ')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات سئو تگ')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات سئو تگ')),
                ('description_ar', models.TextField(null=True, verbose_name='توضیحات سئو تگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو تگ')),
                ('tags_seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.tags')),
            ],
            options={
                'verbose_name': 'سئو تگ',
                'verbose_name_plural': 'سئو تگ',
            },
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('standard_aashto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.standardaashto')),
                ('standard_astm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.standardastm')),
                ('standard_isiri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.standardisiri')),
            ],
            options={
                'verbose_name': 'استانداردها',
                'verbose_name_plural': 'استانداردها',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مشخصه محصول')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='نام مشخصه محصول')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='نام مشخصه محصول')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='نام مشخصه محصول')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار مشخصه محصول')),
                ('value_fa', models.CharField(max_length=255, null=True, verbose_name='مقدار مشخصه محصول')),
                ('value_en', models.CharField(max_length=255, null=True, verbose_name='مقدار مشخصه محصول')),
                ('value_ar', models.CharField(max_length=255, null=True, verbose_name='مقدار مشخصه محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product')),
            ],
            options={
                'verbose_name': 'مشخصات محصولات',
                'verbose_name_plural': 'مشخصات محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سئو محصول')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو محصول')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو محصول')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو محصول')),
                ('description', models.TextField(verbose_name='توضیحات سئو محصول')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات سئو محصول')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات سئو محصول')),
                ('description_ar', models.TextField(null=True, verbose_name='توضیحات سئو محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='عکس سئو محصول')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
            options={
                'verbose_name': 'سئو محصولات',
                'verbose_name_plural': 'سئو محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='نوع رسانه')),
                ('media_type_fa', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True, verbose_name='نوع رسانه')),
                ('media_type_en', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True, verbose_name='نوع رسانه')),
                ('media_type_ar', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True, verbose_name='نوع رسانه')),
                ('media_file', models.FileField(upload_to='product_media/%Y/%m', verbose_name='فایل مدیا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.product')),
            ],
            options={
                'verbose_name': 'تصاویر محصولات',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.productcategorymodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.ManyToManyField(related_name='استاندارد', to='product.standards'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='product.tags'),
        ),
        migrations.CreateModel(
            name='CategorySEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سئو دسته بندی')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو دسته بندی')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو دسته بندی')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان سئو دسته بندی')),
                ('description', models.TextField(verbose_name='توضیحات سئو دسته بندی')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات سئو دسته بندی')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات سئو دسته بندی')),
                ('description_ar', models.TextField(null=True, verbose_name='توضیحات سئو دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='تصویر سئو دسته بندی')),
                ('Category_seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category')),
            ],
            options={
                'verbose_name': 'سئو دسته بندی',
                'verbose_name_plural': 'سئو دسته بندی',
            },
        ),
    ]
