# Generated by Django 4.2 on 2024-11-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type_ar',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type_en',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type_fa',
        ),
    ]
