# Generated by Django 4.2 on 2024-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Code',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
