# Generated by Django 4.2 on 2024-12-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('last_update', models.CharField(max_length=255)),
                ('last_changes', models.DateTimeField(auto_now=True)),
                ('selected_products', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
