# Generated by Django 4.2 on 2024-11-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productmedia_media_type_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardaashto',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='standardaashto',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='standardaashto',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='standardastm',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='standardastm',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='standardastm',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='standardisiri',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='standardisiri',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='standardisiri',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='standards',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='standards',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='standards',
            name='title_fa',
        ),
    ]
