# Generated by Django 4.2 on 2024-12-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_pageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfigProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('page_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_config_products', to='product.pageconfig')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
