# Generated by Django 4.2 on 2024-11-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_standardaashto_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_views',
            field=models.IntegerField(blank=True, default='14', null=True, verbose_name='مجموع بازدید'),
        ),
    ]
