# Generated by Django 4.2 on 2024-12-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_pageconfigproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageconfig',
            name='selected_products',
        ),
    ]
