# Generated by Django 4.2 on 2024-12-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_pageconfig_selected_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageconfig',
            options={'verbose_name': 'لیست قیمتها', 'verbose_name_plural': 'لیست قیمتها'},
        ),
    ]
