# Generated by Django 4.2 on 2024-12-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_updated_at_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
